config/routes.rb
Rails.application.routes.draw do
  resources :bands, only: [:index, :show]
  resources :musicians, only: [:index, :show]
  resources :band_members, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  has_many :band_members
  has_many :musicians, through: :band_members

  def average_age
    musicians.average(:age).to_int
  end

  def order_musicians_by_age
    band_members.includes(:musician).order('musicians.age DESC')
  end
end

app/models/band_member.rb
class BandMember < ApplicationRecord
  validates :instrument, length: { minimum: 3 }
  validates :musician_id, uniqueness: { scope: :band_id, message: 'can only be listed in the same band once' }

  belongs_to :band
  belongs_to :musician
end

app/models/musician.rb
class Musician < ApplicationRecord
  has_many :band_members
  has_many :bands, through: :band_members

  def self.order_by_band_number
    band_count = all.includes(:bands).each_with_object(Hash.new { |h, k| h[k] = [] }) do |m, hash|
      hash[m.bands.size] << m
    end

    sorted_desc = band_count.sort_by { |k, v| -k }
    sorted_desc.map { |arr| arr[1] }.flatten
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/band_members_controller.rb
class BandMembersController < ApplicationController
  def new
    @band_member = BandMember.new
  end

  def create
    @band_member = BandMember.new(band_member_params)

    if @band_member.save
      redirect_to band_path(@band_member.band)
    else
      render :new
    end
  end

  private
  
  def band_member_params
    params.require(:band_member).permit(:band_id, :musician_id, :instrument)
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
  end

  def show
    @band = Band.find_by_id(params[:id])
  end
end

app/controllers/musicians_controller.rb
class MusiciansController < ApplicationController
  def index
    @musicians = Musician.order_by_band_number
  end

  def show
    @musician = Musician.find_by_id(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/band_members/new.html.erb
<h1>New Band Member</h1>

<%= form_for @band_member do |f| %>
  <%= f.label 'Band' %>
  <%= f.collection_select :band_id, Band.all, :id, :name %>

  <%= f.label 'Musician' %>
  <%= f.collection_select :musician_id, Musician.all, :id, :name %>

  <%= f.label :instrument %>
  <%= f.text_field :instrument %>

  <%= f.submit %>
<% end %>

<% if @band_member.errors %>
  <ul>
    <% @band_member.errors.full_messages.each do |m| %>
      <li><%= m %></li>
    <% end %>
  </ul>
<% end %>

app/views/bands/index.html.erb
<h1>Bands</h1>
<ul>
  <% @bands.each do |band| %>
    <li><%= link_to band.name, band_path(band) %></li>
  <% end %>
</ul>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>
<p>Average age: <%= @band.average_age %></p>

<ul>
  <% @band.order_musicians_by_age.each do |member| %>
    <li><%= link_to member.musician.name, musician_path(member.musician) %> <%= member.instrument %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bands</title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Baloo+Chettan+2:800&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/musicians/index.html.erb
<h1>Musicians</h1>

<ul>
  <% @musicians.each do |musician| %>
    <li><%= link_to musician.name, musician_path(musician) %></li>
  <% end %>
</ul>

app/views/musicians/show.html.erb
<h1><%= @musician.name %></h1>

<p>Age: <%= @musician.age %></p>

<ul>
  <% @musician.band_members.each do |member| %>
    <li><%= link_to member.band.name, band_path(member.band) %></li>
  <% end %>
</ul>